name: Build and Release AAR

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build AAR
        run: ./gradlew :shortmesh-ui:assembleRelease

      - name: Create Release and Upload AAR
        uses: softprops/action-gh-release@v1
        with:
          files: shortmesh-ui/build/outputs/aar/shortmesh-ui-release.aar

      - name: List files
        run: ls -R

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}